default: &default
  active_record_encryption_key: <%= ENV['ACTIVE_RECORD_ENCRYPTION_KEY'] || "f259c25474dcef60b68211c7c7c77933f4a6826c2c467ed017c6b006fca33616" %>
  active_record_encryption_key_derivation_salt: <%= ENV['ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT'] || "9fed9ef8a4ee9f41f698ff5a968a6368" %>
  active_record_encryption_deterministic_key: <%= ENV['ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY'] || "70b07682d825e432216df6fe9ee6ba54" %>
  razorpay_key_id: <%= ENV['RAZORPAY_KEY_ID'] || "70b07682fdsffssffe9ee6ba54" %>
  razorpay_key_secret: <%= ENV['RAZORPAY_KEY_SECRET'] || "70b07sdf2216df6fe9ee6ba54" %>

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  s3_bucket: "E_shop-test"
  s3_access_key_id: "DUMMY_S3_ACCESS_KEY_ID"
  s3_secret_access_key: "DUMMY_S3_SECRET_ACCESS_KEY"
  encryption_key: "DUMMY_ENCRYPTION_KEY"

# Do not keep production secrets in the repository,
# instead read values from the environment. Rails.application.secrets
production:
  <<: *default
